# Generated by Django 2.2 on 2022-09-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_code', models.CharField(max_length=10, verbose_name='District code')),
                ('county_code', models.CharField(db_index=True, max_length=10, verbose_name='County code')),
                ('county_name', models.CharField(max_length=255, verbose_name='County')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_code', models.CharField(db_index=True, max_length=10, verbose_name='District code')),
                ('district_name', models.CharField(max_length=255, verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='District')),
                ('county_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='County')),
                ('county_code', models.CharField(db_index=True, max_length=10, verbose_name='County code')),
                ('district_code', models.CharField(db_index=True, max_length=10, verbose_name='District code')),
                ('country_name', models.CharField(blank=True, max_length=20, verbose_name='Country')),
                ('locality_name', models.CharField(blank=True, max_length=125, verbose_name='Locality')),
                ('locality_code', models.CharField(blank=True, max_length=10, verbose_name='Locality code')),
                ('artery_type', models.CharField(blank=True, max_length=255, null=True)),
                ('prep1', models.CharField(blank=True, max_length=255, null=True)),
                ('artery_title', models.CharField(blank=True, max_length=255, null=True)),
                ('prep2', models.CharField(blank=True, max_length=255, null=True)),
                ('artery_name', models.CharField(blank=True, max_length=255, null=True)),
                ('artery_local', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.IntegerField(blank=True, db_index=True, help_text='cp4', verbose_name='Postal Code')),
                ('postal_code_extension', models.IntegerField(blank=True, db_index=True, help_text='cp3', verbose_name='Postal Code Extension')),
                ('postal_designation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Postal Designation')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Postal Code',
                'verbose_name_plural': 'Postal Codes',
            },
        ),
    ]
